### ISSUE TITLE
API Episodes endpoint returning incorrect segments for external programs 

### ISSUE THREAD

**Issue by sdillingham** [SCPR/SCPRv4#234] opened 2015-01-25 23:19 UTC
This appears to be an issue only for External Programs that are ingesting content from the NPR API, specifically ATC and Morning Edition. I suspect this could be an artifact of our recent switch to ElasticSearch.

For example, the website display for a recent episode of ATC shows a full rundown of segments:

http://www.scpr.org/programs/all-things-considered/2015/01/24/7680/

while the API response for the same episode returns a single segment over and over:

http://www.scpr.org/api/v2/episodes/?program=all-things-considered&air_date=2015-01-24

The issue is the same for the v3 API as well.

**Comment by ewr** [comment] 2015-01-25 23:36
Yeah, that's going to be the same caching issue we hit on assets. It'll be a quick fix.

ER

On Jan 25, 2015, at 6:19 PM, Sean Dillingham <notifications@github.com<mailto:notifications@github.com>> wrote:


This appears to be an issue only for External Programs that are ingesting content from the NPR API, specifically ATC and Morning Edition. I suspect this could be an artifact of our recent switch to ElasticSearch.

For example, the website display for a recent episode of ATC shows a full rundown of segments:

http://www.scpr.org/programs/all-things-considered/2015/01/24/7680/

while the API response for the same episode returns a single segment over and over:

http://www.scpr.org/api/v2/episodes/?program=all-things-considered&air_date=2015-01-24

The issue is the same for the v3 API as well.

-

**Comment by ewr** [comment] 2015-01-26 12:17
Resolved via 85ed672677782bd38d6a0df5fcf865ab152a27c0 and de8d2a3a291ab7b50fd508caf2f87d575880edfb. A missing `updated_at` on `ExternalSegment.to_article` was giving us an invalid cache key.

**Closed by ewr** 2015-01-26 12:17 UTC
