### ISSUE TITLE
Find STR for AdTech email link failures

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#408] opened 2016-01-14 17:43 UTC
AC: There are clear steps to reproduce for what causes AdTech ad links in e-mails to fail.

**Comment by Ravenstine** [comment] 2016-01-15 21:41
So far, I am not sure how to reproduce this problem consistently.  It does happen on Brian and Vijay's computers, especially when opening the link from within Gmail.  It tends to happen once and then the link actually redirects.  I thought about adding a trailing forward-slash to the link URL, and this did not change anything for me but it caused Vijay to experience the redirect failure every time.  

All of us are using the same browser versions(Chrome 47 and Safari 9.0.2).  Despite clearing the cache, logging out of AdTech, etc, I have no problems on my end.  The most consistent way to recreate the issue is to open the link through Gmail in Safari.  Brian experienced the issue by opening the link in Chrome through the Outlook native Mac app.

**Comment by ewr** [comment] 2016-01-15 22:03
I would send an email to adtech support. 

ADTECH-US Support <adtech-us-support@adtech.com>

**Comment by Ravenstine** [comment] 2016-01-15 22:24
Waiting to hear back from AdTech...

**Comment by Ravenstine** [comment] 2016-01-19 18:04
I corresponded with a guy from AdTech, and here's what he said:

```
Hi Ben,
 
Yes – that’s perfect, thanks. I can see the tag and it doesn’t have any parameters - it’s just a basic image tag. For newsletters, the tag needs to have a “guid” and “cookie” parameter added to the URL in both the img and anchor elements.
 
I’ve added a new tag type to your network with these parameters already present - it’s called “Email Newsletter Image Tag”
 
Feel free to either use this new tag or just insert the new parameter in to your existing tags. Below is the tag with the important parameters highlighted:
 
<!-- Image Tag (Tag for Images only) //TAG for network 5511: Southern California Public Radio // Website: Newsletters // Page: Test Newsletter // Placement: Test Newsletter-top-300 x 50 (3856755)  // created at: Jan 15, 2016 6:30:04 PM  -->
<a href="http://adserver.adtechus.com/adlink|3.0|5511|3856755|0|711|ADTECH;key=key1+key2+key3+key4;grp=[group];cookie=no;guid=[guid]" target="_blank"><img src="http://adserver.adtechus.com/adserv|3.0|5511|3856755|0|711|ADTECH;key=key1+key2+key3+key4;grp=[group];cookie=no;guid=[guid]" border="0" height="50" width="300" alt="[Alt-Text]"></a>
<!-- End of Image Tag -->
 
This instructs the system to avoid attempting to set cookies and instead use the given guid to correlate the impression and click. The next step is to replace the [guid] placeholder with an identifier of some kind that is unique per recipient. Most email newsletter services have a way to incorporate a value like this in to the email. A common example would be a hash of the recipient email address, or you could just use random numbers. It doesn’t have to be the same across emails to the same recipient.
 
Let me know if you have any questions.
```

**Comment by sdillingham** [comment] 2016-01-19 20:03
Eloqua has a merge field called "Unique Recipient ID" that might work for the GUID. Typically the syntax to merge a field into an email is:

`<span class="eloquaemail" >recipientid</span>`

Try that and see if it does the trick.

**Comment by Ravenstine** [comment] 2016-01-27 17:50
@sdillingham @ewr Can we decide whether or not AdTech is a viable solution for us?  I didn't get much feedback on the last test I sent out, but Eric tried it and said that the clickthrough didn't work at first until the images loaded, but it worked after the images loaded(as opposed to before where the link would never work).  This is probably an edge case, IMO, since most people will wait long enough for the images to load rather than knowing where to immediately click.

**Comment by sdillingham** [comment] 2016-01-27 17:52
@Ravenstine - other than clickthrough not working when images don't load (which I agree is an edge case), any other STR that produce a failed clickthrough?

**Comment by Ravenstine** [comment] 2016-01-27 18:07
@sdillingham There doesn't seem to be, as long as we use the GUID and have the refractory period turned off.  I also tested on my android phone and was able to get a clickthrough as long as I could ping both links in order; it also worked when I shortened the links with bit.ly.

**Comment by Ravenstine** [comment] 2016-02-01 17:21
I'm going to close this for now.

The steps to reproduce the problem are to have the refractory period enabled in AdTech, open a sent email with an AdTech tag, and click on the redirect link before the image has successfully loaded(i.e. before an impression has been made).  Also, a cookie based link can possibly create issues(though I doubt this was what was causing our problem).

The solution is to disable the refractory period(done), use GUIDs in our links, and count on the majority of our users waiting for images to load before clicking on the link.

**Closed by Ravenstine** 2016-02-01 17:21 UTC
Labels: dept-underwriting
