### ISSUE TITLE
Outpost breadcrumb incorrectly resolves after Rails 4.2 upgrade

### ISSUE THREAD

**Issue by ewr** [SCPR/SCPRv4#262] opened 2015-05-07 19:21 UTC
After pushing the Rails 4.2 upgrade, the top-level Outpost breadcrumb link resolves to `/` instead of `/outpost/`.

**Comment by sdillingham** [comment] 2015-05-18 22:34
Related to this issue, Outpost is also writing the logout link incorrectly when you're below the top-level outpost route (e.g. `/outpost/news_stories/` vs. just `/outpost/`). As a result, users hit a 404 when they try to log out and their session is kept alive even though they think they've successfully signed out.

![screen shot 2015-05-18 at 3 32 52 pm](https://cloud.githubusercontent.com/assets/442483/7691892/28c179a4-fd73-11e4-9af7-3afadcd913df.png)

**Comment by Ravenstine** [comment] 2015-05-26 20:33
Just thought I'd briefly touch on this issue.

The only way I could get the outpost routes to "work properly" was to add a sub-path to the path where the engine is mounted.

So instead of:

```ruby
mount Outpost::Engine => '/outpost', as: 'outpost'
```

something like:

```ruby
mount Outpost::Engine => '/outpost/main', as: 'outpost'
```

Now the links created by the Outpost::Engine fall under "/outpost/main" instead of root, even when navigating below the top-level route.  I'm not sure I understand why but I've yet to find another way.  Will still continue to look later.

**Comment by ewr** [comment] 2015-05-26 20:36
Yeah, changing the route shouldn't be how this gets closed. 

It's quite possible this is a Rails bug. I had spent some time tracking down a similar issue for secretary during the 4.2 work, but ended up working around it via a completely senseless order change in the routes.

**Comment by Ravenstine** [comment] 2015-05-29 16:13
I tried some various re-ordering but that didn't seem to change things, unfortunately.  It doesn't seem like this is expected behavior that's documented anywhere.

**Comment by ewr** [comment] 2015-05-29 16:42
Yeah, I believe it's a Rails router bug. I'll try to help you figure out where we need to dig in on that.

**Comment by Ravenstine** [comment] 2015-06-29 16:20
By the way, I tried to poke into the breadcrumbs issue; while I haven’t narrowed down exactly how this is happening(there are so many levels of method calls), I can toggle it inside ActionDispatch::Routing::RoutesProxy(routes_proxy.rb:32).  When the path helpers are generated, they are set to take arguments; those include a “url_options” hash plus whatever arguments are passed in when the helper is actually used.  In the case of logout_path, that’s nothing.

When we are getting the right behavior(the outpost root path), one of the options is “:script_name”, which contains a string “/outpost”, which gives us the correct root path.  When on a deeper level, say News Stories, this ''':script_name''' attribute is set to a blank string, giving us a root path of “/“ and thus a logout URL of “/logout” instead of “/outpost/logout”.  

If I delete the “:script_name” key from that hash, we get the correct URL resolved to “/outpost/logout”.

I’m just focusing on the logout_path because it’s just a single example of the problem that I can test against.  I know there are other links that don’t resolve correctly.

With the time I had, I couldn’t quite figure out where the :script_name key was getting set.  But this makes me wonder a few things: Did older versions of ActionPack/ActionDispatch omit the :script_name key if the value was blank?  Or are we really missing a :script_name value that should be there?  I wonder this because we somehow get the correct path if that option is omitted.

@ewr: If at some point you have the time, I’m wondering what your input might be and what direction I should be taking in figuring this out.  So far I’ve been placing pry-byebug breakpoints in places that seem to make sense in order to try and understand what’s happening.

To further illustrate:

```ruby
# args = [{:host=>"localhost", :port=>3000, :protocol=>"http://", :_recall=>{:controller=>"outpost/news_stories", :action=>"index"}, :script_name=>""}]
routes.url_helpers.logout_path(*args)
# => "/logout"

# args = [{:host=>"localhost", :port=>3000, :protocol=>"http://", :_recall=>{:controller=>"outpost/news_stories", :action=>"index"}, :script_name=>"/outpost"}]
routes.url_helpers.logout_path(*args)
# => "/outpost/logout"

# args = [{:host=>"localhost", :port=>3000, :protocol=>"http://", :_recall=>{:controller=>"outpost/news_stories", :action=>"index"}}]
routes.url_helpers.logout_path(*args)
# => "/outpost/logout"
```

**Comment by Ravenstine** [comment] 2015-06-29 22:39
More progress:

Rails::Engine assigns the script name to ```env["ROUTES_#{routes.object_id}_SCRIPT_NAME"]``` in railties/lib/rails/engine.rb:516.  

That script name gets assigned to the url_options in actionpack/lib/routing/url_for.rb:41.  However, this only ever happens if the same_origin is false, the request itself doesn't already have the "SCRIPT_NAME" value, and the environment does not have an "ORIGINAL_SCRIPT_NAME" value set.  What I don't understand about this is that I've yet to find a situation where same_origin is false(which would mean that the current routes don't match those of the ENV) and request.script_name isn't nil(it defaults to a blank string, which is truthy).  So basically, I don't know that it ever reaches the script name that is specifically set by the Engine.

Here's what the engine does:

```ruby
env["ROUTES_#{routes.object_id}_SCRIPT_NAME"] = env['SCRIPT_NAME'].dup
```

and here's what ActionController#url_for does:

```ruby
    def url_options
      @_url_options ||= {
        :host => request.host,
        :port => request.optional_port,
        :protocol => request.protocol,
        :_recall => request.path_parameters
      }.merge!(super).freeze

      if (same_origin = _routes.equal?(env["action_dispatch.routes".freeze])) ||
         (script_name = env["ROUTES_#{_routes.object_id}_SCRIPT_NAME"]) ||
         (original_script_name = env['ORIGINAL_SCRIPT_NAME'.freeze])

        options = @_url_options.dup
        if original_script_name
          options[:original_script_name] = original_script_name
        else
          options[:script_name] = same_origin ? request.script_name.dup : script_name
        end
        options.freeze
      else
        @_url_options
      end
    end
```

What makes things more confusing is that the engine seems to get called multiple times, sometimes with an environment SCRIPT_NAME and sometimes not.

The following change, while certainly not the solution, seems to produce the expected result:

```ruby
      if (same_origin = _routes.equal?(env["action_dispatch.routes".freeze]))
         script_name = env["ROUTES_#{_routes.object_id}_SCRIPT_NAME"]
         original_script_name = env['ORIGINAL_SCRIPT_NAME'.freeze]

        options = @_url_options.dup
        if original_script_name
          options[:original_script_name] = original_script_name
        else
          options[:script_name] = script_name
        end
        options.freeze
      else
        @_url_options
      end
```

The above change makes the outpost links resolve to the correct path and doesn't seem to have any negative impact on other links in SCPRv4.  

I've been comparing the code I've been looking at to the code in older releases of Rails but I still have not found exactly what is creating this problem.  The code in #url_for just isn't different enough in the last Rails version we were using(4.0.10) before we upgraded to 4.2.

**Comment by Ravenstine** [comment] 2015-06-30 15:51
Issue has now been posted in rails/rails with a reproduce-able example.  If we can't figure this out on our own, hopefully that will help us figure out what the deal is with this behavior.

https://github.com/rails/rails/issues/20738

**Comment by Ravenstine** [comment] 2016-03-10 18:10
Honestly, I think this is worth writing a pull request for.  The change that I made seemed to resolve the error and the other guys' solution also worked.  I ran his example with Rails 5 and the issue still exists there.  If there's a pull request, even if it's not entirely correct(by Rails core team standards), it may help to prod them into actually addressing it.

**Comment by Ravenstine** [comment] 2016-03-22 22:40
Someone on the Rails team moved the issue out of `stale` and added some relevant tags.  I left a comment about how the problem is still unresolved in Rails 5.  I'm going to move this out of my To Do column and just keep an eye on what happens.  It little or nothing happens over this next sprint, I'll attempt a pull request.  However, there's plenty of information for someone better-experienced to do the right thing.

**Comment by Ravenstine** [comment] 2017-02-08 21:51
#759 FIXED

**Closed by Ravenstine** 2017-02-08 21:51 UTC
Labels: bug
