### ISSUE TITLE
Latest News alternate feed for Google News on Assistant

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/SCPRv4#1373] opened 2018-12-05 19:59 UTC
AC
- [ ] bump up LUFS levels so that it's within the -16 to -19 LUFS range (audio is currently too soft)

**Comment by arellaTV** [comment] 2018-12-05 20:29
The first two AC shouldn't be too difficult and should take a couple of minutes each. The last AC requires a bit of research on my part.

A quick (possibly naive) idea is that we could create a copy of the audio presented in the feed somewhere else, modify the volume and reprocess it, and return the new audio files. It would require a recurring job, or perhaps a job that invokes whenever the feed is updated.

I'll check in with how Ben did the volume update for Alexa and update here with what I've learned. Putting this as a 2pt research (for the last AC).

**Comment by arellaTV** [comment] 2018-12-06 18:56
Ah! Looks like I can use this: https://github.com/SCPR/newscast-to-flash-briefing-transcoder

**Comment by arellaTV** [comment] 2018-12-07 23:04
Going to go ahead and move the first two AC to this ticket: https://github.com/SCPR/SCPRv4/issues/1375

**Comment by nakedsushi** [comment] 2018-12-26 18:14
Update: @arellaTV The module not found errors -- I think the issue is building the LAME node libraries. When we build on our dev machines (osx) it uses the osx architecture bindings, but lambda runs on a different physical machine on AWS.  I think I can use docker to build LAME and NPM libraries on ubuntu and see if that works.

**Comment by arellaTV** [comment] 2019-01-03 23:34
In process of code review: https://github.com/SCPR/lambda-podbooster/pull/1

**Comment by arellaTV** [comment] 2019-01-08 00:39
Link to the new PR that fixes errors when uploading a large audio file: https://github.com/SCPR/lambda-podbooster/pull/1

**Comment by arellaTV** [comment] 2019-01-09 18:35
PR merged, lambda running in production. Here's the new podboosted xml: https://s3-us-west-1.amazonaws.com/kpcc-flash-briefing/google-assistant/index.xml

**Closed** 2019-01-09 19:42 UTC
Labels: dept-product, feature
